name: Studio 637 Photography
favicon: null
layout_spectrum: 0.5306269810535014
typography_spectrum: 0.36620313534513116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6540684811770916
  lightness: 0.9466649447567761
  saturation: 0.3745223097503185
  rhythmicContrast: 0.7067296931054443
purpose: []
